project_id = "smart-content"

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["http://127.0.0.1:3000/**"]
enable_signup = true

[auth.email]
enable_signup = true
enable_confirmations = true

[auth.hook.before_user_created]
enabled = true
uri = "pg-functions://postgres/public/before_user_created"
